server:
  port: 8200
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zonsh?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    #url: jdbc:mysql://127.0.0.1:3306/zonsh?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: zonsh654321
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/

mybatis-plus:
  mapper-locations: classpath:user/mapper/xml/*.xml
  type-aliases-package: user.entity
  global-config:
    db-config:
      #驼峰下划线转换
      column-underline: true
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

feign:
  hystrix:
    enabled: true

#请求处理的超时时间
ribbon.ReadTimeout: 120000
#请求连接的超时时间
ribbon.ConnectTimeout: 30000